### ISSUE TITLE
Surprising position of a paragraph after a tag

### ISSUE THREAD

**Issue by gpetiot** [jonludlam/odoc-parser-test#1]
Hi, we have encountered a surprising behavior after using odoc-parser 0.9.0 (https://github.com/ocaml-ppx/ocamlformat/issues/1719), it looks like after parsing a tag, the following paragraphs are added to the list of paragraphs of said tag.

There is a corresponding test in odoc-parser's testbase:
https://github.com/ocaml-doc/odoc-parser/blob/c5ce41b1e1841a2005bb3c4ca3bf1f77876d509d/test/test.ml#L3537-L3546

Is this really expected or should it be 2 different items in the odoc AST?

**Comment by jonludlam** [comment]
Looking at the docs [here](https://ocaml.org/manual/ocamldoc.html#ss:ocamldoc-tags) it seems that the `@deprecated` tag is followed by [text](https://ocaml.org/manual/ocamldoc.html#ss:ocamldoc-formatting) which includes blank lines separating paragraphs. My reading of that is that the test case is correct - what do you think?

**Comment by gpetiot** [comment]
I had the feeling (and some other people too, based on the way they wrote their doc comments) that since the `bar` line was separated with 2 linebreaks from the `@deprecated foo` tag (and indented on the same column, but I don't know if relevant), then it would be considered a different item instead of being a child of this tag.

```
@deprecated foo
      bar                       // same item
```
```
@deprecated foo

bar                     // different item
```

Or maybe there is something in the odoc grammar to indicate the end of a paragraph attached to a tag?

**Comment by jonludlam** [comment]
It seems to me that the expectation is that tags are at the end of doc comments - see the comment [here](https://github.com/ocaml-doc/odoc-parser/blob/main/src/syntax.ml#L602-L603). As such I think there's no way to return a result looking like `[ Paragraph _; Tag _; Paragraph _ ]`

**Comment by gpetiot** [comment]
Alright if that's expected I'm happy to close this issue then, thanks!
