### ISSUE TITLE
Dependency cycle with camlp-streams and odoc

### ISSUE THREAD

**Issue by hra687261** [jonludlam/odoc-parser-test#9]
The latest release of odoc-parser uses camlp-streams which in turn uses odoc which uses odoc-parser.
https://opam.ocaml.org/packages/odoc-parser/
https://opam.ocaml.org/packages/camlp-streams/
https://opam.ocaml.org/packages/odoc/

**Comment by jonludlam** [comment]
I'm going to bat this one to @dra27 !

**Comment by jonludlam** [comment]
This has been fixed, I believe.
